### ISSUE TITLE
Server build fails with code 127 on Fedora 36

### ISSUE THREAD

**Issue by nrwahl2** [WonderTix/WonderTix#187]
1. `README.md` says in multiple locations to run `setup.py`. There is no such file.
2. `sudo docker-compose up` fails as follows. Fairly certain all instructions were followed.
```
$ sudo docker-compose up
WARNING: The PG_DB variable is not set. Defaulting to a blank string.
WARNING: The PG_PASS variable is not set. Defaulting to a blank string.
WARNING: The PG_USER variable is not set. Defaulting to a blank string.
WARNING: The PRIVATE_STRIPE_KEY variable is not set. Defaulting to a blank string.
WARNING: The FRONTEND_URL variable is not set. Defaulting to a blank string.
WARNING: The AUTH0_AUDIENCE variable is not set. Defaulting to a blank string.
WARNING: The AUTH0_URL variable is not set. Defaulting to a blank string.
WARNING: The PUBLIC_STRIPE_KEY variable is not set. Defaulting to a blank string.
WARNING: The AUTH0_CLIENT_ID variable is not set. Defaulting to a blank string.
Building server
Sending build context to Docker daemon  442.9kB
Step 1/7 : FROM node:18-alpine
 ---> 6f44d13dd258
Step 2/7 : RUN apk upgrade --update-cache --available &&     apk add openssl &&     rm -rf /var/cache/apk/*
 ---> Running in 38a5cb4805dd
Error relocating /lib/ld-musl-x86_64.so.1: RELRO protection failed: Permission denied
Error relocating /bin/sh: RELRO protection failed: Permission denied
The command '/bin/sh -c apk upgrade --update-cache --available &&     apk add openssl &&     rm -rf /var/cache/apk/*' returned a non-zero code: 127
ERROR: Service 'server' failed to build : Build failed
```

**Comment by nrwahl2** [comment]
This particular problem goes away when I set SELinux to permissive mode. I'd argue that lack of out-of-box support for running the app with SELinux in enforcing mode is a bug.

After setting SELinux to permissive mode, I got a ton of Node warnings but was able to install. However, the bring-up is still having problems:
```
WARNING: The PG_DB variable is not set. Defaulting to a blank string.
WARNING: The PG_PASS variable is not set. Defaulting to a blank string.
WARNING: The PG_USER variable is not set. Defaulting to a blank string.
WARNING: The PRIVATE_STRIPE_KEY variable is not set. Defaulting to a blank string.
WARNING: The FRONTEND_URL variable is not set. Defaulting to a blank string.
WARNING: The ROOT_URL variable is not set. Defaulting to a blank string.
WARNING: The PUBLIC_STRIPE_KEY variable is not set. Defaulting to a blank string.
Recreating wondertix_client_1   ... done
Recreating wondertix_server_1   ... done
Recreating wondertix_database_1 ... done
Attaching to wondertix_database_1, wondertix_server_1, wondertix_client_1
database_1  | Error: Database is uninitialized and superuser password is not specified.
database_1  |        You must specify POSTGRES_PASSWORD to a non-empty value for the
database_1  |        superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
database_1  | 
database_1  |        You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
database_1  |        connections without a password. This is *not* recommended.
database_1  | 
database_1  |        See PostgreSQL documentation about "trust":
database_1  |        https://www.postgresql.org/docs/current/auth-trust.html
wondertix_database_1 exited with code 1
server_1    | 
server_1    | > wtix-backend@1.0.0 dev
server_1    | > nodemon --exec npx ts-node ./src/server.ts
server_1    | 
server_1    | [nodemon] 2.0.22
server_1    | [nodemon] to restart at any time, enter `rs`
server_1    | [nodemon] watching path(s): *.*
server_1    | [nodemon] watching extensions: ts,json
server_1    | [nodemon] starting `npx ts-node ./src/server.ts`
client_1    | 
client_1    | > wondertix-crm@0.1.0 start
client_1    | > cross-env HTTPS=true cross-env SSL_CRT_FILE=localhost.pem react-scripts start
client_1    | 
server_1    | DB_HOST: 172.17.0.1
client_1    | (node:40) [DEP_WEBPACK_DEV_SERVER_HTTPS] DeprecationWarning: 'https' option is deprecated. Please use the 'server' option.
client_1    | (Use `node --trace-deprecation ...` to show where the warning was created)
client_1    | (node:40) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
client_1    | (node:40) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
server_1    | Error: ENOENT: no such file or directory, open '/wondertix/localhost-key.pem'
server_1    |     at Object.openSync (node:fs:590:3)
server_1    |     at Object.readFileSync (node:fs:458:35)
server_1    |     at Object.<anonymous> (/wondertix/src/server.ts:72:19)
server_1    |     at Module._compile (node:internal/modules/cjs/loader:1267:14)
server_1    |     at Module.m._compile (/wondertix/node_modules/ts-node/src/index.ts:1618:23)
server_1    |     at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
server_1    |     at Object.require.extensions.<computed> [as .ts] (/wondertix/node_modules/ts-node/src/index.ts:1621:12)
server_1    |     at Module.load (node:internal/modules/cjs/loader:1125:32)
server_1    |     at Function.Module._load (node:internal/modules/cjs/loader:965:12)
server_1    |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {
server_1    |   errno: -2,
server_1    |   syscall: 'open',
server_1    |   code: 'ENOENT',
server_1    |   path: '/wondertix/localhost-key.pem'
server_1    | }
server_1    | [nodemon] app crashed - waiting for file changes before starting...
client_1    | Starting the development server...
client_1    | 
client_1    | Failed to compile.
client_1    | 
client_1    | [eslint] 
client_1    | src/components/CRM/Tasks/Filter.tsx
client_1    |   Line 24:9:  Unknown property 'sx' found  react/no-unknown-property
client_1    | 
client_1    | src/components/CRM/Tasks/Note.tsx
client_1    |   Line 12:7:  Unknown property 'sx' found  react/no-unknown-property
client_1    | 
client_1    | src/components/Ticketing/cart/CartItem.tsx
client_1    |   Line 51:57:  Unknown property 'aira-label' found  react/no-unknown-property
client_1    | 
client_1    | Search for the keywords to learn more about each error.
client_1    | assets by path static/ 7.39 MiB
client_1    |   assets by path static/js/*.js 6.96 MiB
client_1    |     asset static/js/bundle.js 6.95 MiB [emitted] (name: main) 1 related asset
client_1    |     asset static/js/node_modules_web-vitals_dist_web-vitals_js.chunk.js 7.24 KiB [emitted] 1 related asset
client_1    |   assets by path static/media/ 440 KiB
client_1    |     asset static/media/S5A5574X_web.0b42f233979bb8fccea6.jpg 429 KiB [emitted] [immutable] [from: src/assets/S5A5574X_web.jpg] (auxiliary name: main)
client_1    |     asset static/media/2011_Logo_white.c13c470d7748f823d2c3.png 11.1 KiB [emitted] [immutable] [from: src/Logo/2011_Logo_white.png] (auxiliary name: main)
client_1    | asset index.html 1.68 KiB [emitted]
client_1    | asset asset-manifest.json 648 bytes [emitted]
client_1    | orphan modules 1.5 MiB [orphan] 974 modules
client_1    | runtime modules 32.8 KiB 17 modules
client_1    | cacheable modules 5.26 MiB (javascript) 440 KiB (asset)
client_1    |   modules by path ./node_modules/ 4.53 MiB 896 modules
client_1    |   modules by path ./src/ 752 KiB (javascript) 440 KiB (asset)
client_1    |     modules by path ./src/components/ 634 KiB 86 modules
client_1    |     asset modules 13.8 KiB (javascript) 440 KiB (asset) 4 modules
client_1    |     modules by path ./src/*.tsx 16.5 KiB 2 modules
client_1    |     modules by path ./src/*.css 74.6 KiB 2 modules
client_1    |     modules by path ./src/Logo/*.css 3.88 KiB 2 modules
client_1    |     ./src/reportWebVitals.ts 1.36 KiB [built] [code generated]
client_1    |     ./src/utils/arrays.tsx 8.41 KiB [built] [code generated]
client_1    | 
client_1    | ERROR in [eslint] 
client_1    | src/components/CRM/Tasks/Filter.tsx
client_1    |   Line 24:9:  Unknown property 'sx' found  react/no-unknown-property
client_1    | 
client_1    | src/components/CRM/Tasks/Note.tsx
client_1    |   Line 12:7:  Unknown property 'sx' found  react/no-unknown-property
client_1    | 
client_1    | src/components/Ticketing/cart/CartItem.tsx
client_1    |   Line 51:57:  Unknown property 'aira-label' found  react/no-unknown-property
client_1    | 
client_1    | Search for the keywords to learn more about each error.
client_1    | 
client_1    | webpack 5.80.0 compiled with 1 error in 10906 ms
client_1    | No issues found.
```

**Comment by samkhodak** [comment]
Readme has been updated with new instructions to build with correct .env variables.
